version: '2'

services:
    configuration:
        container_name: configuration
        image: spiroid/cozy-conf
        build: ./images/cozy-conf

    couchdata:
        container_name: couchdata
        image: spiroid/cozy-couchdb-data
        build: ./images/cozy-couchdb-data

    indexerdata:
        container_name: indexerdata
        image: spiroid/cozy-indexer-data
        build: ./images/cozy-indexer-data

    couchdb:
        image: spiroid/cozy-couchdb
        build: ./images/cozy-couchdb
        restart: always
        volumes_from:
            - couchdata
            - configuration

    controller:
        image: spiroid/cozy-controller
        build: ./images/cozy-controller
        restart: always
        links:
            - couchdb
        volumes_from:
            - configuration
            - indexerdata

    nginx:
        image: spiroid/cozy-nginx
        build: ./images/cozy-nginx
        restart: always
        links:
            - controller
        ports:
            - "443:443"
