version: '2'

volumes:
    couchdata:
        driver: local
    indexerdata:
        driver: local

services:
    couchdb:
        image: klaemo/couchdb:1.6.1
        restart: always
        volumes:
            - couchdata:/usr/local/var/lib/couchdb
        environment:
            - COUCHDB_USER
            - COUCHDB_PASSWORD

    controller:
        image: spiroid/cozy-controller:refactor-v2
        build: ./images/cozy-controller
        restart: always
        volumes:
            - indexerdata:/usr/local/var/cozy/data-system/indexes
        environment:
            - COUCHDB_USER
            - COUCHDB_PASSWORD

    nginx:
        image: spiroid/cozy-nginx
        build: ./images/cozy-nginx
        restart: always
        ports:
            - "443:443"
